FROM node:22-alpine as build

WORKDIR /app

COPY PACKAGE*.JSON ./
RUN npm install

COPY . .

RUN npm run build

FROM node:22-alpine as production

WORKDIR /app

COPY --from=build /app/dist ./dist

RUN npm rebuild bcrypt --build-from-source

CMD [ "npm", "run", "start:prod" ]