# Stage 1: Build
FROM node:22-alpine as build

WORKDIR /app

COPY package*.json ./
RUN apk add --no-cache python3 make g++ \
    && npm install

COPY . .

RUN npm run build

# Stage 2: Production
FROM node:22-alpine as production

WORKDIR /app

COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
COPY package*.json ./

# Rebuild bcrypt for the correct architecture
RUN npm rebuild bcrypt --build-from-source

CMD [ "npm", "run", "start:prod" ]