FROM node:22-alpine as development

WORKDIR /app 

COPY package*.json ./

RUN apk add --no-cache python3 make g++ \
    && npm install \
    && npm rebuild bcrypt --build-from-source

COPY . .

CMD [ "npm", "run", "start:dev" ]