services:
  app-dev:
    container_name: app-dev
    build:
      context: .
      dockerfile: DockerFile.dev
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - dev

  app-prod:
    container_name: app-prod
    build:
      context: .
      dockerfile: DockerFile.prod
    env_file:
      - .env.production
    ports:
      - "8080:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    profiles:
      - prod

  db:
    image: "postgres:17-alpine"
    container_name: app-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: companyDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: "dpage/pgadmin4"
    container_name: app-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  db-data: {}